fix flaky fetch tests
napari/npe2 pull request #255
Opened 2022-11-15 03:12 UTC by nclack

Two test issues here:

It seems like hitting the pypi and hub api's failed to return napari-svg sometimes.  For pypi this is about 1 out of every 2 or 3 attempts.  For hub it's rarer.  Not quite sure why it's happening.  There's meaningful data in the response either way, but sometimes `napari-svg` isn't in the return. Not sure what the best fix is here. For now, I just check that the response data is non-empty.

The fetch-cli test was failing because it's looking at `napari-omero` which has a unicode red exclamation mark in it's package metadata. This causes character validation errors where the encoding of the string is unspecified. This is fixed by specifying 'utf-8' in a couple places in the pr.

2022-11-15 03:57 UTC, nclack commented
Not sure why `napari tests` is failing.

Maybe `disable_notification_dismiss_timer` in conftest is causing problems 😕

2022-11-15 23:32 UTC, kne42 approved these changes
lgtm

2022-11-16 01:18 UTC, andy-sweet requested changes
No problem with the code changes, but you'll need to fix the napari tests before merging. As discussed offline, I think one way to do this is make a PR to `napari/napari` that moves `disable_notification_dismiss_timer` to `test_qt_notifications.py`, so that it's only auto-used in that test module (which shouldn't be run here).

2022-11-30 20:10 UTC, aganders3 commented
I don't really know why I ended up looking into this, but it looks like the issue is scraping PyPI defaulting to "Most Relevant" sorting which seems to be unstable. This might ultimately be a warehouse bug because that kinda sucks even if you're using a browser. Ordering by "Date last updated" seems to fix it (at least I was able to run 331 times in a row without the failure):

```diff
diff --git a/npe2/_inspection/_fetch.py b/npe2/_inspection/_fetch.py
index 23e2d76..bf4a5b0 100644
--- a/npe2/_inspection/_fetch.py
+++ b/npe2/_inspection/_fetch.py
@@ -384,7 +384,7 @@ def _get_packages_by_classifier(classifier: str) -> Dict[str, str]:
 
     packages = {}
     page = 1
-    url = f"https://pypi.org/search/?c={parse.quote_plus(classifier)}&page="
+    url = f"https://pypi.org/search/?q=&o=-created&c={parse.quote_plus(classifier)}&page="
     while True:
         try:
             with request.urlopen(f"{url}{page}") as response:
```

With the above change (note 264 is the number of plugins the web interface reports as well):
```
>>> for i in range(10):
...     print(len(get_pypi_plugins()))
... 
264
264
264
264
264
264
264
264
264
264
```

Without this change:
```
>>> for i in range(10):
...     print(len(get_pypi_plugins()))
... 

251
251
251
263
250
250
251
251
251
251
```

2022-11-30 21:01 UTC, aganders3 commented
Another option would be to use the (to-be-deprecated) XML RPC API:
https://warehouse.pypa.io/api-reference/xml-rpc.html#browse-classifiers

2022-11-30 21:23 UTC, aganders3 commented
> Another option would be to use the (to-be-deprecated) XML RPC API:
https://warehouse.pypa.io/api-reference/xml-rpc.html#browse-classifiers

This might be the way - it's also super fast (~300 ms vs ~6s). The results seem to already be sorted but I'm not sure this is guaranteed and it's natural sorted so a bit different from the current implementation but that would be an easy fix. I'm _pretty sure_ the version sorting is okay so this works but we might want to iterate the results to make sure.

```diff
diff --git a/npe2/_inspection/_fetch.py b/npe2/_inspection/_fetch.py
index 23e2d76..d1a1b69 100644
--- a/npe2/_inspection/_fetch.py
+++ b/npe2/_inspection/_fetch.py
@@ -6,6 +6,7 @@ import os
 import re
 import subprocess
 import tempfile
+import xmlrpc.client
 from concurrent.futures import ProcessPoolExecutor
 from contextlib import contextmanager
 from functools import lru_cache
@@ -376,27 +377,11 @@ def _get_packages_by_classifier(classifier: str) -> Dict[str, str]:
 
     Returns
     -------
-    packages : List[str]
+    packages : Dict[str, str]
         name of all packages at pypi that declare ``classifier``
     """
-    PACKAGE_NAME_PATTERN = re.compile('class="package-snippet__name">(.+)</span>')
-    PACKAGE_VERSION_PATTERN = re.compile('class="package-snippet__version">(.+)</span>')
-
-    packages = {}
-    page = 1
-    url = f"https://pypi.org/search/?c={parse.quote_plus(classifier)}&page="
-    while True:
-        try:
-            with request.urlopen(f"{url}{page}") as response:
-                html = response.read().decode()
-            names = PACKAGE_NAME_PATTERN.findall(html)
-            versions = PACKAGE_VERSION_PATTERN.findall(html)
-            packages.update(dict(zip(names, versions)))
-            page += 1
-        except error.HTTPError:
-            break
-
-    return dict(sorted(packages.items()))
+    client = xmlrpc.client.ServerProxy('https://pypi.org/pypi')
+    return dict(client.browse([classifier]))
```

2022-12-13 17:22 UTC, nclack commented
napari/napari#5388 fixed the last remaining issue I was having

2022-12-13 17:31 UTC, nclack commented
@aganders3 Thanks for looking into the xmlrpc api!  

Given that it's on the way to deprecation, do you still think that's the right approach?  Is there a simple api equivalent?

2022-12-13 19:18 UTC, aganders3 commented
I'm not sure - there's a bit of history here including past requests from napari: https://github.com/pypi/warehouse/issues/9156. Their timeline is very vague but I would suspect they will not remove it until there is an equivalent new API. If not I would hope for a concrete deprecation period to be announced at some point.

One idea is to use the XML RPC API and fall back on the current method. The XML RPC API has some methods already deprecated that now raise a `RuntimeError` so we can probably anticipate the same path. I'm likewise not too confident in the stability of the interface we're currently scraping, but there doesn't seem to be a clear path forward for this capability.

Regardless I think it could be saved for another PR - for now I guess I would just recommend adding the change proposed in my other comment above https://github.com/napari/npe2/pull/255#issuecomment-1332683255. It's small and could be added here or I can make another PR for that.

2022-12-15 00:22 UTC, merged